const direccionUsuarioSchema = {
  DireccionUsuario: {
    type: 'object',
    properties: {
      ID: { type: 'integer' },
      usuario_id: { type: 'string' },
      TIPO_ZONA: { type: 'string', nullable: true },
      DIRECCION_RESIDENCIA: { type: 'string', nullable: true },
      DIRECCION_LABORAL: { type: 'string', nullable: true },
      DIRECCION_CTA_EXT: { type: 'string', nullable: true },
      CIUDAD_RESIDENCIA: { type: 'string', nullable: true },
      DEPARTAMENTO_RESIDENCIA: { type: 'string', nullable: true },
      PAIS_RESIDENCIA: { type: 'string', nullable: true },
      CIUDAD_LABORAL: { type: 'string', nullable: true },
      DEPARTAMENTO_LABORAL: { type: 'string', nullable: true },
      PAIS_LABORAL: { type: 'string', nullable: true },
      CIUDAD_CTA_EXT: { type: 'string', nullable: true },
      PAIS_CTA_EXT: { type: 'string', nullable: true },
      BARRIO: { type: 'string', nullable: true },
      TELEFONO: { type: 'string', nullable: true },
      TELEFONO_LABORAL: { type: 'string', nullable: true },
      TELEFONO_RESIDENCIA: { type: 'string', nullable: true },
      ADDRESSLINE_CELULAR: { type: 'string', nullable: true },
      ADDRESSLINE_MAIL: { type: 'string', nullable: true },
      BANCO_CTA_EXT: { type: 'string', nullable: true },
      NRO_CTA_EXT: { type: 'string', nullable: true },
      MANEJA_CTA_EN_MONEDA_EXTRANJERA: { type: 'boolean', nullable: true },
    },
  },
  DireccionUsuarioInput: {
    type: 'object',
    required: ['usuario_id'],
    properties: {
      TIPO_ZONA: { type: 'string' },
      DIRECCION_RESIDENCIA: { type: 'string' },
      DIRECCION_LABORAL: { type: 'string' },
      DIRECCION_CTA_EXT: { type: 'string' },
      CIUDAD_RESIDENCIA: { type: 'string' },
      DEPARTAMENTO_RESIDENCIA: { type: 'string' },
      PAIS_RESIDENCIA: { type: 'string' },
      CIUDAD_LABORAL: { type: 'string' },
      DEPARTAMENTO_LABORAL: { type: 'string' },
      PAIS_LABORAL: { type: 'string' },
      CIUDAD_CTA_EXT: { type: 'string' },
      PAIS_CTA_EXT: { type: 'string' },
      BARRIO: { type: 'string' },
      TELEFONO: { type: 'string' },
      TELEFONO_LABORAL: { type: 'string' },
      TELEFONO_RESIDENCIA: { type: 'string' },
      ADDRESSLINE_CELULAR: { type: 'string' },
      ADDRESSLINE_MAIL: { type: 'string' },
      BANCO_CTA_EXT: { type: 'string' },
      NRO_CTA_EXT: { type: 'string' },
      MANEJA_CTA_EN_MONEDA_EXTRANJERA: { type: 'boolean' },
    },
  },
};

export default direccionUsuarioSchema;
